### ISSUE TITLE
Strings defined in external file

### ISSUE THREAD

**Issue by cfenell** [danielk333/pypaper#1]
My BibTeX file uses strings defined in a separate file strings,bib.
This gives rise to an undefined string error, like this:
 bibtexparser.bibdatabase.UndefinedString: 'grl'

**Comment by danielk333** [comment]
I had forgot transfer of strings in the pickup, now fixed!

**Comment by danielk333** [comment]
Possible additional problem if there are cross-referring code in picked up bib-files

**Comment by danielk333** [comment]
Thought about it over lunch and think this fixes all possible issues with strings
